### ISSUE TITLE
MongDB Jira Epic

### ISSUE THREAD

**Issue by crobinson42** [anzairyo0127/mongodb-connection-bug#1]
This will be fixed here: https://jira.mongodb.org/browse/NODE-2267

**Comment by anzairyo0127** [comment]
@crobinson42 
Use machine translation. I'm sorry if it's strange English.

Thank you for contacting me. I confirmed the contents of the link.
I will also link to the `readme.md` of this repository.

**Comment by anzairyo0127** [comment]
I confirmed in Ver 3.3.5 that TimeOut Error has been resolved.
